version: 0.2

phses:
  install:
    commands:
      # install Node 12
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - sudo apt-get install -y nodejs
  pre-build:
    commands:
      # install dependencies
      - echo installing dependencies...
      - npm i
  build:
    commands:
      # build
      - echo Building...
      - npm run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist
